import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { NodeServices } from "@effect/platform-node"
import type { BotId, OrgId } from "@evie/contracts/ids"
import { botDir, resolveHome } from "@evie/shared/home"
import { Effect, Layer } from "effect"
import { afterAll, describe, expect, it } from "vitest"
import { EvieConfig } from "../src/config.ts"
import { Scaffold } from "../src/provider/scaffold.ts"

/**
 * A bot has to know what it can do.
 *
 * Left with only the three-line `instructions.md` the scaffold used to write,
 * a bot answered questions about its own runtime from the base model's priors
 * -- and got them wrong in the direction that costs the most: it told a user
 * it could not run anything on a schedule, while Evie's Routines scheduler was
 * sitting one table over, cron and IANA timezone and all.
 *
 * So the briefing is Evie-owned and regenerated per spawn, not user-owned and
 * written once. These tests pin the two halves that make that work: it lands
 * where eve will actually read it, and it never touches the user's file.
 *
 * `regenerate` is the whole surface under test -- it writes files and shells
 * out to nothing, so there is no install and no subprocess here.
 *
 * Temp directory, never `~/.evie` -- see rule 2 in AGENTS.md.
 */

const root = mkdtempSync(join(tmpdir(), "evie-briefing-"))
afterAll(() => rmSync(root, { recursive: true, force: true }))

const home = resolveHome({ EVIE_HOME: root } as NodeJS.ProcessEnv)

const ConfigTest = Layer.succeed(EvieConfig, {
  home,
  bind: "127.0.0.1",
  port: 0,
  mode: "local",
  idleStopMinutes: 10,
  flags: { persistReasoning: false },
})

const ScaffoldTest = Scaffold.layer.pipe(Layer.provide([ConfigTest, NodeServices.layer]))

const orgId = "org_1" as OrgId

/** A bot directory as it exists before this change: scaffolded, no briefing. */
const seedBot = (botId: BotId, instructions: string) => {
  const dir = botDir(home, orgId, botId)
  mkdirSync(join(dir, "agent", "channels"), { recursive: true })
  mkdirSync(join(dir, "agent", "sandbox"), { recursive: true })
  writeFileSync(join(dir, "agent", "instructions.md"), instructions, "utf8")
  return dir
}

const run = <A, E>(effect: Effect.Effect<A, E, Scaffold>) =>
  Effect.runPromise(effect.pipe(Effect.provide(ScaffoldTest)) as Effect.Effect<A, E, never>)

describe("capability briefing", () => {
  it("lands in agent/instructions/, where eve reads it after the user's file", async () => {
    const botId = "bot_reads" as BotId
    const dir = seedBot(botId, "# Ada\n\nYou are Ada.\n")

    await run(Effect.flatMap(Scaffold, (scaffold) => scaffold.regenerate({ orgId, botId })))

    // eve reads `agent/instructions/` non-recursively and applies entries in
    // filename order after the root file, so the name is load-bearing: `00-`
    // keeps Evie's briefing ahead of anything the user adds beside it.
    const briefing = readFileSync(join(dir, "agent", "instructions", "00-evie.md"), "utf8")
    expect(briefing).toContain("Generated by Evie")
  })

  it("tells the bot it can be scheduled, which is the answer it used to get wrong", async () => {
    const botId = "bot_cron" as BotId
    const dir = seedBot(botId, "# Grace\n\nYou are Grace.\n")

    await run(Effect.flatMap(Scaffold, (scaffold) => scaffold.regenerate({ orgId, botId })))

    const briefing = readFileSync(join(dir, "agent", "instructions", "00-evie.md"), "utf8")
    // Routines are Evie's scheduler, not eve's `agent/schedules/`, and the
    // briefing has to name the one that actually fires under `eve dev`.
    expect(briefing).toMatch(/routine/i)
    expect(briefing).toMatch(/cron/i)
    expect(briefing).toMatch(/do not answer a scheduling question with a flat "no"/i)

    // Names where the user actually does it. "Yes, schedules exist somewhere"
    // is the same unhelpful answer wearing a better mood.
    expect(briefing).toMatch(/Routines.{0,40}sidebar/is)

    // And still stops short of the opposite error: creating one is the user's
    // action, not a tool the bot holds, so it must not imply it set one up.
    expect(briefing).toMatch(/cannot create the routine yourself/i)
  })

  it("tells the bot a connected service's tools are real, and which kind are not", async () => {
    const botId = "bot_conns" as BotId
    const dir = seedBot(botId, "# Ida\n\nYou are Ida.\n")

    await run(Effect.flatMap(Scaffold, (scaffold) => scaffold.regenerate({ orgId, botId })))

    const briefing = readFileSync(join(dir, "agent", "instructions", "00-evie.md"), "utf8")
    expect(briefing).toContain("connection_search")
    // Member-scoped connections still have no OAuth proxy, so the briefing has
    // to name the half that does not work -- otherwise a bot confidently
    // reports tools it was never given.
    expect(briefing).toMatch(/per-member connections.{0,60}not wired up/is)
    // And the standing rule that outlives both: the tool list wins.
    expect(briefing).toMatch(/trust your live tool list/i)
  })

  it("leaves the user's instructions.md alone", async () => {
    const botId = "bot_owned" as BotId
    const persona = "# Ada\n\nYou are Ada. Never use exclamation marks.\n"
    const dir = seedBot(botId, persona)

    await run(Effect.flatMap(Scaffold, (scaffold) => scaffold.regenerate({ orgId, botId })))

    // The whole reason the briefing is a separate file: this one is the user's,
    // and a regenerate that rewrote it would eat their persona on every boot.
    expect(readFileSync(join(dir, "agent", "instructions.md"), "utf8")).toBe(persona)
  })

  it("is idempotent, because every runtime spawn rewrites it", async () => {
    const botId = "bot_twice" as BotId
    const dir = seedBot(botId, "# Linus\n\nYou are Linus.\n")
    const briefingPath = join(dir, "agent", "instructions", "00-evie.md")

    await run(Effect.flatMap(Scaffold, (scaffold) => scaffold.regenerate({ orgId, botId })))
    const first = readFileSync(briefingPath, "utf8")
    await run(Effect.flatMap(Scaffold, (scaffold) => scaffold.regenerate({ orgId, botId })))

    expect(readFileSync(briefingPath, "utf8")).toBe(first)
  })

  it("refuses a directory that was never scaffolded", async () => {
    const botId = "bot_missing" as BotId

    const outcome = await run(
      Effect.flatMap(Scaffold, (scaffold) =>
        scaffold.regenerate({ orgId, botId }).pipe(Effect.result),
      ),
    )

    // A spawn maps this to a StartError rather than booting a bot whose
    // generated files silently never landed.
    expect(outcome._tag).toBe("Failure")
  })
})
