/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppNewRouteImport } from './routes/_app.new'
import { Route as AppPluginsRouteImport } from './routes/_app.plugins'
import { Route as AppRoutinesRouteImport } from './routes/_app.routines'
import { Route as WelcomeConnectRouteImport } from './routes/welcome_.connect'
import { Route as AppChatThreadIdRouteImport } from './routes/_app.chat.$threadId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPluginsRoute = AppPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesRoute = AppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppRoute,
} as any)
const WelcomeConnectRoute = WelcomeConnectRouteImport.update({
  id: '/welcome_/connect',
  path: '/welcome/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatThreadIdRoute = AppChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/welcome': typeof WelcomeRoute
  '/new': typeof AppNewRoute
  '/plugins': typeof AppPluginsRoute
  '/routines': typeof AppRoutinesRoute
  '/welcome/connect': typeof WelcomeConnectRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeRoute
  '/new': typeof AppNewRoute
  '/plugins': typeof AppPluginsRoute
  '/routines': typeof AppRoutinesRoute
  '/welcome/connect': typeof WelcomeConnectRoute
  '/': typeof AppIndexRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_app/new': typeof AppNewRoute
  '/_app/plugins': typeof AppPluginsRoute
  '/_app/routines': typeof AppRoutinesRoute
  '/welcome_/connect': typeof WelcomeConnectRoute
  '/_app/': typeof AppIndexRoute
  '/_app/chat/$threadId': typeof AppChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/new'
    | '/plugins'
    | '/routines'
    | '/welcome/connect'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/welcome'
    | '/new'
    | '/plugins'
    | '/routines'
    | '/welcome/connect'
    | '/'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/_app'
    | '/welcome'
    | '/_app/new'
    | '/_app/plugins'
    | '/_app/routines'
    | '/welcome_/connect'
    | '/_app/'
    | '/_app/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  WelcomeConnectRoute: typeof WelcomeConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plugins': {
      id: '/_app/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof AppPluginsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines': {
      id: '/_app/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AppRoutinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/welcome_/connect': {
      id: '/welcome_/connect'
      path: '/welcome/connect'
      fullPath: '/welcome/connect'
      preLoaderRoute: typeof WelcomeConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat/$threadId': {
      id: '/_app/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AppChatThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppNewRoute: typeof AppNewRoute
  AppPluginsRoute: typeof AppPluginsRoute
  AppRoutinesRoute: typeof AppRoutinesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatThreadIdRoute: typeof AppChatThreadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNewRoute: AppNewRoute,
  AppPluginsRoute: AppPluginsRoute,
  AppRoutinesRoute: AppRoutinesRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatThreadIdRoute: AppChatThreadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  WelcomeConnectRoute: WelcomeConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
