import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import type { ReasoningEffort } from "@evie/contracts/bot"
import type { BotId, OrgId } from "@evie/contracts/ids"
import { botDir } from "@evie/shared/home"
import { Context, Effect, Fiber, Layer, Schema, Stream } from "effect"
import { ChildProcess, ChildProcessSpawner } from "effect/unstable/process"
import { EvieConfig } from "../config.ts"

/**
 * Creates and maintains a bot's eve project on disk under
 * `userdata/orgs/<orgId>/bots/<botId>/` (02, "Evie home").
 *
 * Ownership is the whole design here. Evie owns four generated files --
 * `agent/agent.ts`, `agent/channels/eve.ts`, `agent/sandbox/sandbox.ts`, and
 * `agent/instructions/00-evie.md` -- and everything else in `agent/` belongs
 * to the user. `regenerate` therefore rewrites the channel, sandbox, and
 * briefing files; `agent.ts` is edited through
 * `eve set --model … --reasoning …` so eve's own validated source editor stays
 * the single writer and a `defineDynamic` model is never clobbered. And
 * `instructions.md` is written once at creation and never touched again.
 */

/** Pinned per bot directory (decision 014): a bot never changes runtime under you. */
export const EVE_VERSION = "0.38.2"

/**
 * The sandbox VM runtime, pinned exactly for the same reason as eve -- and one
 * more: msb refuses to open a database migrated by a different msb version, so
 * "whatever `^0.5.0` resolves to today" is a boot failure waiting for the day
 * two bots resolve differently. Must satisfy the `microsandbox` peer range of
 * `EVE_VERSION`; bump the two together. Pinning it here also front-loads the
 * download into provisioning, where the creation screen covers it, instead of
 * eve auto-installing it mid-first-turn.
 */
export const MSB_VERSION = "0.5.10"

export class ScaffoldFailure extends Schema.TaggedError<ScaffoldFailure>()("ScaffoldFailure", {
  step: Schema.String,
  detail: Schema.String,
}) {}

/* --- generated sources ------------------------------------------------------ */

const packageJsonSource = (botId: BotId): string =>
  `${JSON.stringify(
    {
      name: `evie-bot-${botId.toLowerCase()}`,
      version: "0.0.0",
      private: true,
      type: "module",
      imports: { "#*": "./agent/*", "#evals/*": "./evals/*" },
      scripts: { build: "eve build", dev: "eve dev", start: "eve start", typecheck: "tsc" },
      dependencies: {
        "@vercel/connect": "0.4.3",
        ai: "^7.0.58",
        eve: EVE_VERSION,
        microsandbox: MSB_VERSION,
        zod: "4.4.3",
      },
      devDependencies: { "@types/node": "24.x", typescript: "7.0.2" },
      overrides: { ai: "^7.0.58" },
      engines: { node: "24.x" },
    },
    null,
    2,
  )}\n`

const tsconfigSource = `${JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      module: "esnext",
      moduleResolution: "bundler",
      strict: true,
      noEmit: true,
    },
    include: ["agent/**/*.ts", "evals/**/*.ts"],
  },
  null,
  2,
)}\n`

const gitignoreSource = `node_modules
.env*
.eve
.output
dist
*.tsbuildinfo
`

const agentSource = (model: string): string => `import { defineAgent } from "eve";

export default defineAgent({ model: ${JSON.stringify(model)} });
`

const instructionsSource = (name: string): string => `# ${name}

You are ${name}. Be helpful, direct, and honest about what you did and did not do.
`

/**
 * The capability briefing, and the reason it is Evie-owned rather than part of
 * `instructions.md`.
 *
 * A bot's own instructions are the user's file, written once and never
 * rewritten, which makes them exactly the wrong place for facts that change
 * when Evie changes. Left to the base model's priors, a bot guesses at its own
 * runtime and guesses badly -- the bug this fixes was a bot flatly answering
 * "no" to whether it could run on a schedule, while Evie's own Routines
 * scheduler sat one table over.
 *
 * eve reads `agent/instructions/` non-recursively and applies entries after
 * the root `instructions.md`, so the user's persona still leads and this only
 * ever appends. Keep it to what is verifiably true of the runtime today: an
 * over-promise here is the same defect in the other direction.
 */
const evieBriefingSource = `<!-- Generated by Evie. Do not edit -- Evie rewrites this file. -->

# Your runtime

You are an agent running on the eve framework, hosted inside Evie. This section
is written by Evie, not by your user, and it describes what you can actually
do. Do not guess at your own capabilities. If a request is outside this list,
say what you would need rather than flatly refusing.

## Tools you already have

Your live tool list is the authority; this is what Evie sets up for you.

- \`bash\` -- run shell commands in your sandbox.
- \`read_file\`, \`write_file\`, \`glob\`, \`grep\` -- files in your sandbox.
- \`web_fetch\` -- fetch a URL. It runs in the app runtime, so the sandbox
  network policy below does not apply to it.
- \`web_search\` -- search the web.
- \`todo\` -- a durable per-session checklist that survives compaction.
- \`ask_question\` -- stop mid-turn, ask the user, continue once they answer.
  Use it on an ambiguous request instead of guessing.
- \`agent\` -- hand a self-contained subtask to a fresh copy of yourself. The
  child shares your tools and sandbox but starts with empty history.
- \`load_skill\` and \`connection_search\` appear only when this bot has skills
  or connections configured.

## Your sandbox

A Linux VM rooted at \`/workspace\`, isolated from the machine Evie runs on.
Install packages, write scripts, run them. It lasts for the session.

Network egress is deny-all except Evie's model gateway plus whatever hosts are
allow-listed for this bot. A blocked request is a setting to change rather than
a dead end, so name the exact host you need instead of giving up -- but do not
send anyone to a specific screen to change it, because the control for it has
not shipped yet.

The sandbox cannot reach your own project files. You cannot edit your own
instructions, skills, or tools from \`bash\`.

## Scheduled work

Evie can run you on a schedule. The mechanism is a **routine**: a saved prompt
that Evie's scheduler fires on a 5-field cron expression, in a stored IANA
timezone, optionally in a specific thread, and as a named "run as" member whose
credentials the unattended run uses. When it fires, Evie dispatches the turn
exactly as a person's message would.

Your user creates one under **Routines** in the sidebar: a cadence (daily,
weekdays, weekly, hourly, every N minutes, or a raw cron expression), a
timezone, and the prompt to run. They can pause, resume, and delete it there
too.

So do not answer a scheduling question with a flat "no". That is wrong, and it
is a mistake bots here have actually made. Say yes, help word the prompt, pick
the cadence, and confirm the timezone, then point at Routines in the sidebar as
where it gets saved. You cannot create the routine yourself -- it is their
action, not a tool you hold -- so say that plainly rather than implying you
have set one up.

A scheduled run has nobody in front of it. Say in the prompt what to do when
there is nothing to report, and do not plan to ask a question mid-run.

Separately, eve's own \`agent/schedules/\` files are a different mechanism and
never fire here, because Evie runs this bot with \`eve dev\`. Routines are the
only scheduling that works in Evie.

## Connections

Your user can connect an external service (MCP or OpenAPI) to you in Evie.
Its tools then become yours, named \`<connection>__<tool>\` -- use
\`connection_search\` to find them. Connecting or disconnecting one restarts
you, so a service added mid-conversation is available on the next message
rather than this one.

Two limits worth knowing. Org-wide connections work: one credential the whole
organization shares. Per-member connections, where each person signs in with
their own account, are not wired up yet, so one will show as connected and give
you no tools. And a connection whose credential was never filled in fails on
first use with an error naming the variable it wanted.

The rule that follows from all of it: trust your live tool list, never the fact
that something is listed as connected. If a task needs a service and no tool
for it is in your tools, say so instead of pretending to reach it.

## Honesty

Your user chose Evie partly because it does not lie about what it is doing. Do
not claim work you did not do, and do not deny a capability listed here. When
you genuinely cannot do something, say what would unblock it.
`

/* --- connections ------------------------------------------------------------ */

/**
 * The environment variable a generated connection reads its token from.
 *
 * Shared with `Supervisor.spawnEnv`, and it has to be: the file that reads the
 * name and the spawn that sets it are written in two different modules, and a
 * connection whose token is injected under a name nothing reads fails at the
 * first tool call with a 401 that names nothing.
 *
 * Grants are stored as `grant:<connectionId>`, which is deliberately not a
 * legal environment identifier -- see `injectable` in `Supervisor.ts`. That
 * filter exists so a credential is never in the runtime's environment "under a
 * name no generated connection reads". This is the name one does read, so the
 * value arrives here and only here, and only for a connection whose file
 * actually asks for it.
 */
export const connectionEnvName = (name: string): string =>
  `EVIE_CONN_${name.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}`

/** Everything the generator needs about one connection, resolved by the caller. */
export interface ConnectionSpec {
  readonly name: string
  readonly kind: string
  readonly scope: string
  readonly authKind: "none" | "token" | "interactive"
  readonly url: string
  readonly baseUrl?: string | undefined
}

/** The first line of every file Evie writes into `agent/connections/`. */
const GENERATED_MARKER = "// Generated by Evie. Do not edit -- Evie rewrites this file."

/**
 * Whether Evie can write a working file for this connection today.
 *
 * `member` scope and `interactive` auth both mean per-person OAuth, which 05
 * routes through Evie's own `/oauth/callback/:connection` proxy -- and that
 * proxy does not exist yet. Generating a file for one would produce a bot that
 * compiles and then fails at the first tool call, which is strictly worse than
 * a connection that visibly has no tools: the first looks like a broken
 * service, the second looks like the unfinished feature it is.
 */
export const isGeneratable = (spec: ConnectionSpec): boolean =>
  (spec.kind === "mcp" || spec.kind === "openapi") &&
  spec.scope === "org" &&
  spec.authKind !== "interactive"

/**
 * One `agent/connections/<name>.ts`.
 *
 * Only `org` scope reaches here, so the credential is one the whole
 * organization shares and `principalType` stays eve's `"app"` default (05,
 * "Agent → third party"). The token is read inside `getToken` rather than
 * captured at module load, so rotating it is a runtime restart and not a
 * rebuild -- and a connection whose token is missing fails as an auth error
 * naming the variable, instead of as `undefined` reaching an Authorization
 * header.
 */
const connectionSource = (spec: ConnectionSpec): string => {
  const define = spec.kind === "mcp" ? "defineMcpClientConnection" : "defineOpenAPIConnection"
  const target =
    spec.kind === "mcp"
      ? `  url: ${JSON.stringify(spec.url)},`
      : [
          `  spec: ${JSON.stringify(spec.url)},`,
          ...(spec.baseUrl === undefined ? [] : [`  baseUrl: ${JSON.stringify(spec.baseUrl)},`]),
        ].join("\n")

  const envName = connectionEnvName(spec.name)
  const auth =
    spec.authKind === "token"
      ? `  auth: {
    getToken: async () => {
      const token = process.env[${JSON.stringify(envName)}];
      if (!token) {
        throw new Error(
          "${envName} is not set. Link this connection's credential in Evie, then restart the bot.",
        );
      }
      return { token };
    },
  },
`
      : ""

  return `${GENERATED_MARKER}
import { ${define} } from "eve/connections";

export default ${define}({
${target}
  description: ${JSON.stringify(`The ${spec.name} service, connected in Evie.`)},
${auth}});
`
}

/**
 * The generated channel from 05: verifies the per-turn HS256 JWT naming the
 * acting member, so `ctx.session.auth.current` is a real person and
 * member-scoped connections resolve that person's grant.
 */
const channelSource = `// Generated by Evie. Do not edit -- Evie rewrites this file.
import { eveChannel } from "eve/channels/eve";
import { extractBearerToken, verifyJwtHmac, withAuthChallenges, type AuthFn } from "eve/channels/auth";

const evieCaller: AuthFn<Request> = withAuthChallenges(async (request) => {
  const token = extractBearerToken(request.headers.get("authorization"));
  if (!token) return null;
  const result = await verifyJwtHmac(token, {
    algorithm: "HS256",
    issuer: "evie",
    audiences: [process.env.EVIE_BOT_ID!],
    secret: process.env.EVIE_RUNTIME_SECRET!,
  });
  if (!result.ok) return null;

  const claims = result.sessionAuth.attributes;
  return {
    authenticator: "evie",
    principalId: String(claims.sub), // stable Better Auth user id
    principalType: "user", // required for member-scoped connections
    attributes: { orgId: claims.org, role: claims.role, issuer: "evie" },
  };
}, [{ scheme: "Bearer" }]);

export default eveChannel({ auth: [evieCaller] });
`

/**
 * Deny-all plus an explicit allow-list -- Evie's default, stricter than eve's
 * `allow-all` (02, "Per-bot files Evie owns"). The list itself rides in the
 * spawn env, so a Settings change needs a runtime restart, not a file rewrite.
 */
const sandboxSource = `// Generated by Evie from Settings > Computer. Do not edit -- Evie rewrites this file.
import { defineSandbox, defaultBackend } from "eve/sandbox";

export default defineSandbox({
  backend: defaultBackend(),
  async onSession({ use }) {
    await use({
      networkPolicy: {
        // deny-all plus an explicit allow-list. Evie's default, stricter than eve's.
        allow: ["ai-gateway.vercel.sh", ...JSON.parse(process.env.EVIE_ALLOWED_HOSTS ?? "[]")],
      },
    });
  },
});
`

/* --- the service ------------------------------------------------------------- */

export interface CreateBotProjectInput {
  readonly orgId: OrgId
  readonly botId: BotId
  readonly name: string
  readonly model: string
  readonly reasoning?: ReasoningEffort
}

export interface SetModelInput {
  readonly orgId: OrgId
  readonly botId: BotId
  readonly model?: string
  readonly reasoning?: ReasoningEffort
}

export interface ScaffoldShape {
  /** Idempotent: an existing directory keeps every user-owned file, `instructions.md` included. */
  readonly create: (input: CreateBotProjectInput) => Effect.Effect<{ dir: string }, ScaffoldFailure>
  /**
   * Rewrites every Evie-owned file. Never `instructions.md`, never `agent.ts`.
   *
   * `connections` is passed in rather than read here so `Scaffold` stays a file
   * writer with no database behind it -- which is also what lets a test drive
   * the generator directly.
   */
  readonly regenerate: (input: {
    readonly orgId: OrgId
    readonly botId: BotId
    readonly connections?: ReadonlyArray<ConnectionSpec>
  }) => Effect.Effect<void, ScaffoldFailure>
  /** Shells out to `eve set` so eve's validated source editor stays `agent.ts`'s single writer. */
  readonly setModel: (input: SetModelInput) => Effect.Effect<void, ScaffoldFailure>
}

const make = Effect.gen(function* () {
  const config = yield* EvieConfig
  const spawner = yield* ChildProcessSpawner.ChildProcessSpawner

  const write = (step: string, path: string, content: string) =>
    Effect.try({
      try: () => writeFileSync(path, content, "utf8"),
      catch: (cause) => new ScaffoldFailure({ step, detail: String(cause) }),
    })

  const writeIfAbsent = (step: string, path: string, content: string) =>
    existsSync(path) ? Effect.void : write(step, path, content)

  /**
   * Runs one child to completion, draining merged output so a chatty install
   * cannot stall on a full pipe. The handle is scoped: an interrupt kills the
   * process group, per rule 1 -- no PID is ever discovered after the fact.
   */
  const run = Effect.fn("Scaffold.run")(function* (
    step: string,
    dir: string,
    command: string,
    args: ReadonlyArray<string>,
  ) {
    const output = yield* Effect.scoped(
      Effect.gen(function* () {
        const handle = yield* spawner.spawn(
          ChildProcess.make(command, args, { cwd: dir, extendEnv: true }),
        )
        const collect = yield* Effect.forkChild(Stream.mkString(Stream.decodeText(handle.all)))
        const code = yield* handle.exitCode
        const text = yield* Fiber.join(collect)
        return { code: Number(code), text }
      }),
    ).pipe(
      Effect.mapError(
        (cause) => new ScaffoldFailure({ step, detail: `${command} failed to run: ${String(cause)}` }),
      ),
    )
    if (output.code !== 0) {
      return yield* new ScaffoldFailure({
        step,
        detail: `${command} exited with ${output.code}: ${output.text.slice(-2000)}`,
      })
    }
  })

  const dirOf = (orgId: OrgId, botId: BotId) => botDir(config.home, orgId, botId)

  /**
   * `agent/connections/` reconciled to the bot's rows: one file per generatable
   * connection, and nothing else Evie wrote.
   *
   * The sweep is what makes disconnecting work. Without it a removed service
   * keeps its file, keeps its tools, and keeps working -- a revoked
   * integration that is still live is the worst possible direction for this
   * bug to fail in. Only files carrying Evie's marker are removed, so a
   * hand-authored connection in the same directory survives.
   */
  const writeConnections = (dir: string, connections: ReadonlyArray<ConnectionSpec>) =>
    Effect.gen(function* () {
      const connectionsDir = join(dir, "agent", "connections")
      const generatable = connections.filter(isGeneratable)
      const wanted = new Map(generatable.map((spec) => [`${spec.name}.ts`, spec]))

      yield* Effect.try({
        try: () => {
          mkdirSync(connectionsDir, { recursive: true })
          for (const entry of readdirSync(connectionsDir)) {
            if (!entry.endsWith(".ts") || wanted.has(entry)) continue
            const path = join(connectionsDir, entry)
            if (readFileSync(path, "utf8").startsWith(GENERATED_MARKER)) rmSync(path)
          }
        },
        catch: (cause) => new ScaffoldFailure({ step: "connections", detail: String(cause) }),
      })

      for (const [file, spec] of wanted) {
        yield* write("connections", join(connectionsDir, file), connectionSource(spec))
      }
    })

  const writeOwnedFiles = (dir: string, connections: ReadonlyArray<ConnectionSpec>) =>
    Effect.gen(function* () {
      yield* writeConnections(dir, connections)
      yield* write("channel", join(dir, "agent", "channels", "eve.ts"), channelSource)
      yield* write("sandbox", join(dir, "agent", "sandbox", "sandbox.ts"), sandboxSource)
      // mkdir here rather than in `create`: this is the one owned file whose
      // directory a pre-briefing bot does not already have, and `regenerate`
      // has to work on those bots without a separate migration.
      yield* Effect.try({
        try: () => mkdirSync(join(dir, "agent", "instructions"), { recursive: true }),
        catch: (cause) => new ScaffoldFailure({ step: "briefing", detail: String(cause) }),
      })
      // `00-` so the user's own `agent/instructions/` entries sort after it.
      yield* write("briefing", join(dir, "agent", "instructions", "00-evie.md"), evieBriefingSource)
    })

  const setModel: ScaffoldShape["setModel"] = Effect.fn("Scaffold.setModel")(function* (input) {
    const dir = dirOf(input.orgId, input.botId)
    const args = ["set"]
    if (input.model !== undefined) args.push("--model", input.model)
    if (input.reasoning !== undefined) args.push("--reasoning", input.reasoning)
    if (args.length === 1) return
    // The bot-local binary: eve is pinned per bot directory (decision 014).
    yield* run("eve-set", dir, join(dir, "node_modules", ".bin", "eve"), args)
  })

  const create: ScaffoldShape["create"] = Effect.fn("Scaffold.create")(function* (input) {
    const dir = dirOf(input.orgId, input.botId)
    yield* Effect.try({
      try: () => {
        mkdirSync(join(dir, "agent", "channels"), { recursive: true })
        mkdirSync(join(dir, "agent", "sandbox"), { recursive: true })
      },
      catch: (cause) => new ScaffoldFailure({ step: "mkdir", detail: String(cause) }),
    })

    // Written once; the user may add direct-provider deps or edit freely after.
    yield* writeIfAbsent("package.json", join(dir, "package.json"), packageJsonSource(input.botId))
    yield* writeIfAbsent("tsconfig", join(dir, "tsconfig.json"), tsconfigSource)
    yield* writeIfAbsent("gitignore", join(dir, ".gitignore"), gitignoreSource)
    yield* writeIfAbsent("agent", join(dir, "agent", "agent.ts"), agentSource(input.model))
    // The user's file from the moment it exists. Never rewritten, even by create.
    yield* writeIfAbsent(
      "instructions",
      join(dir, "agent", "instructions.md"),
      instructionsSource(input.name),
    )
    // A brand new bot has no connections yet; the first spawn reconciles them.
    yield* writeOwnedFiles(dir, [])

    if (!existsSync(join(dir, ".git"))) {
      yield* run("git-init", dir, "git", ["init", "--quiet"])
    }
    // eve pinned per bot directory means node_modules per bot directory.
    if (!existsSync(join(dir, "node_modules", ".bin", "eve"))) {
      yield* run("install", dir, "npm", ["install", "--no-audit", "--no-fund", "--silent"])
    }
    if (input.reasoning !== undefined) {
      yield* setModel({
        orgId: input.orgId,
        botId: input.botId,
        reasoning: input.reasoning,
      })
    }
    return { dir }
  })

  const regenerate: ScaffoldShape["regenerate"] = Effect.fn("Scaffold.regenerate")(function* (
    input,
  ) {
    const dir = dirOf(input.orgId, input.botId)
    if (!existsSync(join(dir, "agent"))) {
      return yield* new ScaffoldFailure({
        step: "regenerate",
        detail: `${dir} is not a scaffolded bot directory`,
      })
    }
    yield* writeOwnedFiles(dir, input.connections ?? [])
  })

  return { create, regenerate, setModel } satisfies ScaffoldShape
})

export class Scaffold extends Context.Service<Scaffold, ScaffoldShape>()("Scaffold") {
  static readonly layer = Layer.effect(Scaffold, make)
}
