import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import type { ReasoningEffort } from "@evie/contracts/bot"
import type { BotId, OrgId } from "@evie/contracts/ids"
import { botDir } from "@evie/shared/home"
import { Context, Effect, Fiber, Layer, Schema, Stream } from "effect"
import { ChildProcess, ChildProcessSpawner } from "effect/unstable/process"
import { EvieConfig } from "../config.ts"

/**
 * Creates and maintains a bot's eve project on disk under
 * `userdata/orgs/<orgId>/bots/<botId>/` (02, "Evie home").
 *
 * Ownership is the whole design here. Evie owns exactly three generated files
 * -- `agent/agent.ts`, `agent/channels/eve.ts`, `agent/sandbox/sandbox.ts` --
 * and everything else in `agent/` belongs to the user. `regenerate` therefore
 * rewrites only the channel and sandbox files; `agent.ts` is edited through
 * `eve set --model … --reasoning …` so eve's own validated source editor stays
 * the single writer and a `defineDynamic` model is never clobbered. And
 * `instructions.md` is written once at creation and never touched again.
 */

/** Pinned per bot directory (decision 014): a bot never changes runtime under you. */
export const EVE_VERSION = "0.38.2"

/**
 * The sandbox VM runtime, pinned exactly for the same reason as eve -- and one
 * more: msb refuses to open a database migrated by a different msb version, so
 * "whatever `^0.5.0` resolves to today" is a boot failure waiting for the day
 * two bots resolve differently. Must satisfy the `microsandbox` peer range of
 * `EVE_VERSION`; bump the two together. Pinning it here also front-loads the
 * download into provisioning, where the creation screen covers it, instead of
 * eve auto-installing it mid-first-turn.
 */
export const MSB_VERSION = "0.5.10"

export class ScaffoldFailure extends Schema.TaggedError<ScaffoldFailure>()("ScaffoldFailure", {
  step: Schema.String,
  detail: Schema.String,
}) {}

/* --- generated sources ------------------------------------------------------ */

const packageJsonSource = (botId: BotId): string =>
  `${JSON.stringify(
    {
      name: `evie-bot-${botId.toLowerCase()}`,
      version: "0.0.0",
      private: true,
      type: "module",
      imports: { "#*": "./agent/*", "#evals/*": "./evals/*" },
      scripts: { build: "eve build", dev: "eve dev", start: "eve start", typecheck: "tsc" },
      dependencies: {
        "@vercel/connect": "0.4.3",
        ai: "^7.0.58",
        eve: EVE_VERSION,
        microsandbox: MSB_VERSION,
        zod: "4.4.3",
      },
      devDependencies: { "@types/node": "24.x", typescript: "7.0.2" },
      overrides: { ai: "^7.0.58" },
      engines: { node: "24.x" },
    },
    null,
    2,
  )}\n`

const tsconfigSource = `${JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      module: "esnext",
      moduleResolution: "bundler",
      strict: true,
      noEmit: true,
    },
    include: ["agent/**/*.ts", "evals/**/*.ts"],
  },
  null,
  2,
)}\n`

const gitignoreSource = `node_modules
.env*
.eve
.output
dist
*.tsbuildinfo
`

const agentSource = (model: string): string => `import { defineAgent } from "eve";

export default defineAgent({ model: ${JSON.stringify(model)} });
`

const instructionsSource = (name: string): string => `# ${name}

You are ${name}. Be helpful, direct, and honest about what you did and did not do.
`

/**
 * The generated channel from 05: verifies the per-turn HS256 JWT naming the
 * acting member, so `ctx.session.auth.current` is a real person and
 * member-scoped connections resolve that person's grant.
 */
const channelSource = `// Generated by Evie. Do not edit -- Evie rewrites this file.
import { eveChannel } from "eve/channels/eve";
import { extractBearerToken, verifyJwtHmac, withAuthChallenges, type AuthFn } from "eve/channels/auth";

const evieCaller: AuthFn<Request> = withAuthChallenges(async (request) => {
  const token = extractBearerToken(request.headers.get("authorization"));
  if (!token) return null;
  const result = await verifyJwtHmac(token, {
    algorithm: "HS256",
    issuer: "evie",
    audiences: [process.env.EVIE_BOT_ID!],
    secret: process.env.EVIE_RUNTIME_SECRET!,
  });
  if (!result.ok) return null;

  const claims = result.sessionAuth.attributes;
  return {
    authenticator: "evie",
    principalId: String(claims.sub), // stable Better Auth user id
    principalType: "user", // required for member-scoped connections
    attributes: { orgId: claims.org, role: claims.role, issuer: "evie" },
  };
}, [{ scheme: "Bearer" }]);

export default eveChannel({ auth: [evieCaller] });
`

/**
 * Deny-all plus an explicit allow-list -- Evie's default, stricter than eve's
 * `allow-all` (02, "Per-bot files Evie owns"). The list itself rides in the
 * spawn env, so a Settings change needs a runtime restart, not a file rewrite.
 */
const sandboxSource = `// Generated by Evie from Settings > Computer. Do not edit -- Evie rewrites this file.
import { defineSandbox, defaultBackend } from "eve/sandbox";

export default defineSandbox({
  backend: defaultBackend(),
  async onSession({ use }) {
    await use({
      networkPolicy: {
        // deny-all plus an explicit allow-list. Evie's default, stricter than eve's.
        allow: ["ai-gateway.vercel.sh", ...JSON.parse(process.env.EVIE_ALLOWED_HOSTS ?? "[]")],
      },
    });
  },
});
`

/* --- the service ------------------------------------------------------------- */

export interface CreateBotProjectInput {
  readonly orgId: OrgId
  readonly botId: BotId
  readonly name: string
  readonly model: string
  readonly reasoning?: ReasoningEffort
}

export interface SetModelInput {
  readonly orgId: OrgId
  readonly botId: BotId
  readonly model?: string
  readonly reasoning?: ReasoningEffort
}

export interface ScaffoldShape {
  /** Idempotent: an existing directory keeps every user-owned file, `instructions.md` included. */
  readonly create: (input: CreateBotProjectInput) => Effect.Effect<{ dir: string }, ScaffoldFailure>
  /** Rewrites the channel and sandbox files only. Never `instructions.md`, never `agent.ts`. */
  readonly regenerate: (input: {
    readonly orgId: OrgId
    readonly botId: BotId
  }) => Effect.Effect<void, ScaffoldFailure>
  /** Shells out to `eve set` so eve's validated source editor stays `agent.ts`'s single writer. */
  readonly setModel: (input: SetModelInput) => Effect.Effect<void, ScaffoldFailure>
}

const make = Effect.gen(function* () {
  const config = yield* EvieConfig
  const spawner = yield* ChildProcessSpawner.ChildProcessSpawner

  const write = (step: string, path: string, content: string) =>
    Effect.try({
      try: () => writeFileSync(path, content, "utf8"),
      catch: (cause) => new ScaffoldFailure({ step, detail: String(cause) }),
    })

  const writeIfAbsent = (step: string, path: string, content: string) =>
    existsSync(path) ? Effect.void : write(step, path, content)

  /**
   * Runs one child to completion, draining merged output so a chatty install
   * cannot stall on a full pipe. The handle is scoped: an interrupt kills the
   * process group, per rule 1 -- no PID is ever discovered after the fact.
   */
  const run = Effect.fn("Scaffold.run")(function* (
    step: string,
    dir: string,
    command: string,
    args: ReadonlyArray<string>,
  ) {
    const output = yield* Effect.scoped(
      Effect.gen(function* () {
        const handle = yield* spawner.spawn(
          ChildProcess.make(command, args, { cwd: dir, extendEnv: true }),
        )
        const collect = yield* Effect.forkChild(Stream.mkString(Stream.decodeText(handle.all)))
        const code = yield* handle.exitCode
        const text = yield* Fiber.join(collect)
        return { code: Number(code), text }
      }),
    ).pipe(
      Effect.mapError(
        (cause) => new ScaffoldFailure({ step, detail: `${command} failed to run: ${String(cause)}` }),
      ),
    )
    if (output.code !== 0) {
      return yield* new ScaffoldFailure({
        step,
        detail: `${command} exited with ${output.code}: ${output.text.slice(-2000)}`,
      })
    }
  })

  const dirOf = (orgId: OrgId, botId: BotId) => botDir(config.home, orgId, botId)

  const writeOwnedFiles = (dir: string) =>
    Effect.gen(function* () {
      yield* write("channel", join(dir, "agent", "channels", "eve.ts"), channelSource)
      yield* write("sandbox", join(dir, "agent", "sandbox", "sandbox.ts"), sandboxSource)
    })

  const setModel: ScaffoldShape["setModel"] = Effect.fn("Scaffold.setModel")(function* (input) {
    const dir = dirOf(input.orgId, input.botId)
    const args = ["set"]
    if (input.model !== undefined) args.push("--model", input.model)
    if (input.reasoning !== undefined) args.push("--reasoning", input.reasoning)
    if (args.length === 1) return
    // The bot-local binary: eve is pinned per bot directory (decision 014).
    yield* run("eve-set", dir, join(dir, "node_modules", ".bin", "eve"), args)
  })

  const create: ScaffoldShape["create"] = Effect.fn("Scaffold.create")(function* (input) {
    const dir = dirOf(input.orgId, input.botId)
    yield* Effect.try({
      try: () => {
        mkdirSync(join(dir, "agent", "channels"), { recursive: true })
        mkdirSync(join(dir, "agent", "sandbox"), { recursive: true })
      },
      catch: (cause) => new ScaffoldFailure({ step: "mkdir", detail: String(cause) }),
    })

    // Written once; the user may add direct-provider deps or edit freely after.
    yield* writeIfAbsent("package.json", join(dir, "package.json"), packageJsonSource(input.botId))
    yield* writeIfAbsent("tsconfig", join(dir, "tsconfig.json"), tsconfigSource)
    yield* writeIfAbsent("gitignore", join(dir, ".gitignore"), gitignoreSource)
    yield* writeIfAbsent("agent", join(dir, "agent", "agent.ts"), agentSource(input.model))
    // The user's file from the moment it exists. Never rewritten, even by create.
    yield* writeIfAbsent(
      "instructions",
      join(dir, "agent", "instructions.md"),
      instructionsSource(input.name),
    )
    yield* writeOwnedFiles(dir)

    if (!existsSync(join(dir, ".git"))) {
      yield* run("git-init", dir, "git", ["init", "--quiet"])
    }
    // eve pinned per bot directory means node_modules per bot directory.
    if (!existsSync(join(dir, "node_modules", ".bin", "eve"))) {
      yield* run("install", dir, "npm", ["install", "--no-audit", "--no-fund", "--silent"])
    }
    if (input.reasoning !== undefined) {
      yield* setModel({
        orgId: input.orgId,
        botId: input.botId,
        reasoning: input.reasoning,
      })
    }
    return { dir }
  })

  const regenerate: ScaffoldShape["regenerate"] = Effect.fn("Scaffold.regenerate")(function* (
    input,
  ) {
    const dir = dirOf(input.orgId, input.botId)
    if (!existsSync(join(dir, "agent"))) {
      return yield* new ScaffoldFailure({
        step: "regenerate",
        detail: `${dir} is not a scaffolded bot directory`,
      })
    }
    yield* writeOwnedFiles(dir)
  })

  return { create, regenerate, setModel } satisfies ScaffoldShape
})

export class Scaffold extends Context.Service<Scaffold, ScaffoldShape>()("Scaffold") {
  static readonly layer = Layer.effect(Scaffold, make)
}
